version: "3.9"
services:
  worker:
    build: .
    environment:
      REDIS_URI: $REDIS_URI
      REDIS_PASS: $REDIS_PASSW
      APP_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      ACCESS_CHANNEL: $ACCESS_CHANNEL
      WEBHOOK: $WEBHOOK
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      AUTH_USERS: $AUTH_USERS
      OWNER_ID: $OWNER_ID
      Bot_username: $Bot_username
      
